name: Blocklapse
version: ${project.version}
main: net.nodium.mcplugins.blocklapse.Blocklapse
api-version: 1.15
depend: [ LogBlock ]
authors: [ polymetric ]
description: Allows the creation of timelapses from LogBlock logs.
website: nodium.net/mcplugins/blocklapse
commands:
  blocklapse:
    description: Main Blocklapse command
    usage: /blocklapse <subcommand>
    permission: blocklapse.bl
  bl:
    description: Main Blocklapse command
    usage: /bl <subcommand>
    permission: blocklapse.bl